query getWorkspaceOverviewData($workspaceSlug: Slug!) {
	workspace(slug: $workspaceSlug) {
     id
     name
		 destinations{
			... on Integration{
				name
				metadata{
				 ... on IntegrationMetadata{
						slug
					 }
				}
				id
#				connectedSources{
#					name
#					id
#				}
				settings
			}
			
		}
	}
}